### ISSUE TITLE
Every transformed Ditto has 0 IVs in every stat after being caught

### ISSUE THREAD

**Issue by Vas0sky** [jojobear13/shinpokered#100]
I can't say for the master branch, but catching a ditto after it uses transform it gives it 0 IVs in every stat in the lite branch. I've checked with PkHex the 3 dittos I've caught after they used transform. If you catch a ditto before it uses transform, the IVs will be normally randomized.

**Comment by jojobear13** [comment]
The transformation status bit was being set before the check on whether or not to backup the original IVs (in case the enemy 'mon was already transformed). This resulted in the original IVs never getting backed up. Upon catching, the default 0's in the backup location would become the final IVs. See d20af0350174fad54d6c5fb6e81979eaab8d91b9 for the fix. Slated for next release.
