### ISSUE TITLE
Game crashes at bottom level of Team Rocket hideout

### ISSUE THREAD

**Issue by aluhn2012** [jojobear13/shinpokered#12]
When I take the stairs to the bottom level of Team Rocket's hideout underneath the game corner the screen goes white and none of the buttons have any effect.

**Comment by aluhn2012** [comment]
Oh actually it's Rocket Hideout 3 that causes the game to crash. Not the very bottom level, which would be 4 I guess.

**Comment by jojobear13** [comment]
Need more info. Is this save only from v1.13 or is it from v1.11, v1.112, or earlier.

**Comment by jojobear13** [comment]
> 
> 
> Oh actually it's Rocket Hideout 3 that causes the game to crash. Not the very bottom level, which would be 4 I guess.

Need more info. Is this save only from v1.13 or is it from v1.11, v1.112, or earlier.

**Comment by jojobear13** [comment]
> 
> 
> Oh actually it's Rocket Hideout 3 that causes the game to crash. Not the very bottom level, which would be 4 I guess.

Also post your save file.

**Comment by jojobear13** [comment]
> 
> 
> Oh actually it's Rocket Hideout 3 that causes the game to crash. Not the very bottom level, which would be 4 I guess.

Also, try this if your emulator has a debugger (I use BGB emulator). Go to location D633 of the wram and write 00 to it. Then save the game. This will probably fix the issue.

**Comment by aluhn2012** [comment]
Sorry, I am using open emu and I am not sure how the debugging mode works... I believe the saves should all be from v1.13. Here is my savestate:
[Quick Save State.oesavestate.zip](https://github.com/jojobear13/shinpokered/files/4569190/Quick.Save.State.oesavestate.zip)

**Comment by jojobear13** [comment]
> 
> 
> Sorry, I am using open emu and I am not sure how the debugging mode works... I believe the saves should all be from v1.13. Here is my savestate:
> [Quick Save State.oesavestate.zip](https://github.com/jojobear13/shinpokered/files/4569190/Quick.Save.State.oesavestate.zip)

I can't debug with this. I need at least your .SAV file generated when you save the game.

**Comment by aluhn2012** [comment]
Oh sorry, here you go. .sav file type not supported so you can get it here
https://mega.nz/file/ec0gSIyK#ckE4riD4bWXycf8D913yYt3X_XVedRzsYp0kC76WQlI

**Comment by jojobear13** [comment]
> 
> 
> Oh sorry, here you go. .sav file type not supported so you can get it here
> https://mega.nz/file/ec0gSIyK#ckE4riD4bWXycf8D913yYt3X_XVedRzsYp0kC76WQlI

Fixed the wram location. It was corrupted  from a memory leak that has since been patched.
[http://www.filedropper.com/pokeredbeta](url)

**Comment by aluhn2012** [comment]
Hi, so this fixed the issue with Rocket's hideout that I was having, however I had customized the wild Pokemon's availability to be different from your master version. Now that I am playing with this fixed .sav file it seems to have reverted back to the wild mons availability of your master version. 

Sorry for being troublesome but any guidance you could give on this issue would be helpful. 

Thanks!

**Comment by jojobear13** [comment]
> Hi, so this fixed the issue with Rocket's hideout that I was having, however I had customized the wild Pokemon's availability to be different from your master version. Now that I am playing with this fixed .sav file it seems to have reverted back to the wild mons availability of your master version.
> 
> Sorry for being troublesome but any guidance you could give on this issue would be helpful.
> 
> Thanks!

Wild mon encounter data isn’t stored in the saved data. It’s stored in the rom data, and it gets reloaded each time the map gets loaded. No way to permanently change it without hex editing the rom file, recompiling, or messing with the wram in a debugger.

**Comment by aluhn2012** [comment]
Hi, once again I am sorry for my ignorance in these matters, but I'm not sure I understand. Maybe I do...

If I recompile my edited rom package (with customized mon encounter data) to create a new .gbc game file, but then load my current .sav file in THAT game it might address both issues?

or

Are you saying my issue should not exist in the first place?

or

You're saying that there's no way to keep my customized mon availability and also fix the bug?

As always I appreciate your patience with me and your willingness to help!

**Comment by jojobear13** [comment]
> Hi, once again I am sorry for my ignorance in these matters, but I'm not sure I understand. Maybe I do...
> 
> If I recompile my edited rom package (with customized mon encounter data) to create a new .gbc game file, but then load my current .sav file in THAT game it might address both issues?
> 
> or
> 
> Are you saying my issue should not exist in the first place?
> 
> or
> 
> You're saying that there's no way to keep my customized mon availability and also fix the bug?
> 
> As always I appreciate your patience with me and your willingness to help!

I’m saying it should not exist in the first place. Me editing your sav file cannot create that issue.

**Comment by aluhn2012** [comment]
Right you are! I guess in my attempts to make sure I was playing v1.13 after first encountering the glitch that I accidentally switched my rom over to your master wild mon availability. Easy fix on my end though. Thanks for your patience and help!
