### ISSUE TITLE
Incorrect HM for Butterfree, Venonat, and Venomoth

### ISSUE THREAD

**Issue by wisp92** [jojobear13/shinpokered#137]
I checked online to verify this. In Yellow Butterfree, Venonat, and Venomoth can learn Flash, not Strength. According to the notes in the source, HM 4 was added to Butterfree and Venomoth; it should have been HM 5. Furthermore, HM 5 hasn't been added to Venonat either.

**Comment by jojobear13** [comment]
Oops. It seems my versus guide from 1999 has some typos.
