### ISSUE TITLE
Potential Bug with Disable

### ISSUE THREAD

**Issue by wisp92** [jojobear13/shinpokered#138]
It only happened once in the game, so I am not able to check the exact conditions that it occurs. It seems that sometimes Disable although successful it doesn't disable any of the active PKMN's moves. Although the messages that a move was disabled and enabled a few turns later appear normally. It might be connected to the player changing PKMN in the same turn that Disable hits.

**Comment by jojobear13** [comment]
a few questions: 1) trainer battle or wild battle, and which trainer if applicable? 2) was the player or enemy the one that was disabled?

**Comment by wisp92** [comment]
1) Trainer battle, the first biker on Route 15 entering from Fuchsia City. I let the trainer's PKMN scale with the player, so he had two Weezing and a Grimer in the battle. 2) The enemy's Grimer used Disable to the player.

**Comment by jojobear13** [comment]
A few more questions. Trying to narrow down potential causes. Were none of the player mon's moves listed as "disabled!" in the move selection window. Was the supposedly disabled move usable?

**Comment by wisp92** [comment]
Unfortunately, I went a bit fast with the text, and I only saw the message of the Disable but not which move it targeted. I'll try to recreate the conditions, and post an update.

**Comment by wisp92** [comment]
I tried to recreate the issue by repetitively switching PKMN, but I couldn't trigger the bug again. I can verify that the enemy PKMN disabled successfully each of the four moves (on separate occasions) of the player's active PKMN at the time even after it just switched in. So the bug might not be related to switching at all. If you can't find any evidence in the code, maybe I should notify you again if the problem reoccurs.

**Comment by jojobear13** [comment]
Nothing obvious from my end. The ".AnyMoveDisabledCheck" section works since that handles decrementing the counter and printing the "No Longer Disabled" message. If something is going to cause it, then it's probably going to be in the function that handles the disable move effect itself.

If it happens again, try to upload your rom file somewhere with a save state file. I'll directly check the wram to see what's going on with the disable byte. I use BGB for my emulator, but most emulators like mGBA and such will let me peak at the memory.

**Comment by wisp92** [comment]
I don't see any potential bug there except if the messages for when Disable is executed successfully and for when it fades away have any more conditions other than checking wPlayerDisabledMove.

**Comment by wisp92** [comment]
Not the same issue, but I think you can verify this one. A disabled move has a chance to be enabled again on the same turn disable was used and this has a funny side-effect when the player is slower than the opponent. The player may select a move that subsequently gets disabled by the opponent, this should end up in the selected move failing. However, if the move is enabled on the same turn then the move is actually executed. I believe that either Disable counter should have a minimum of 1 turn but this could potentially overpower the move, or the disablecounter should update on the end of the round to avoid this situation.
