### ISSUE TITLE
Minor Bugs & Suggestions - Part 2

### ISSUE THREAD

**Issue by wisp92** [jojobear13/shinpokered#154]
I checked the last areas I could pre-Championship. Hope these observations help somewhat. I'll post one last Issue if a find anything post-Championship.

Positioning:
1.  The karate master in Viridian City's gym (left side, 2nd trainer from the bottom) has only two tiles line-of-sight. Given his position, GameFreak's initial intention might have been to have three tiles in order to battle the trainer as soon as he lands in the landing tile.

Text:
2. Giovanni's text the 2nd time the player talks to him after winning the Earthbadge is a  bit weird given he is supposed to have already lost to the player's rival. Maybe something "...losing in my peak..." would be more appropriate.

Trainer AI:
3. Not sure of the jugglers' AI level but there are two jugglers in the Victory Road 2F who seem to be goofing sometimes during the battle. The general folklore suggests that in Victory Road all trainers have acquired the 8 Kanto badges and hence there AI level should be appropriate, (4. and 5. is inspired by them, so I don't if higher AI layers avoid these)
4. A juggler used Earthquake to a Flying-type PKMN.
5. A juggler switched in a PKMN with Frozen status. That normally wouldn't be a problem this was the second consecutive switch, and there was no type-mismatch with the player's PKMN.
6. Assuming cool trainers use all AI routines this might have not been implemented yet: Double turn attacks, including Fly, Dig, Sky Attack, Solar Beam, and Skull Bash should not be preferred when the acting PKMN has the Paralyze status, since the chance of them failing is actively doubled. This was observed during the battle with a cool trainer in Victory Road 2F.

**Comment by jojobear13** [comment]
All good suggestions, and I’ll look into them.

With regards to jugglers:
- AI functions and routines are applied per trainer class. Not per individual trainer. So there is no built-in way to only adjust the victory road jugglers.
- Jugglers do not have AI Layer 3, so they do not know how to type-match. They are a less-skilled class of trainer similar to hikers and fishermen.
- Jugglers have a special behavior given by Gamefreak that many don’t seem to know about. Every turn, there is a 50% chance for them to switch no matter what. They “juggle” their active Pokémon.

**Comment by wisp92** [comment]
I thought so about the juggler class. Do you think these two could be replaced by trainers from higher AI classes in the master build given that Victory Road is the final dungeon before the Elite Four? If not maybe their juggling could become a bit smarter even if type-match ability can't be improved due to their AI layer.

**Comment by jojobear13** [comment]
> I thought so about the juggler class. Do you think these two could be replaced by trainers from higher AI classes in the master build given that Victory Road is the final dungeon before the Elite Four? If not maybe their juggling could become a bit smarter even if type-match ability can't be improved due to their AI layer.

I think I’ll take away layer 3 from the burglar class and give it to the juggler. Burglers can be in the same tier as rockets and bikers. 

Layer 4 is intelligent switching, but that goes against the gimmick of the juggler (and might conflict with a few things). He is supposed to randomly “juggle” between his 1st-most and 2nd-most Pokémon in his roster that have hp remaining regardless of anything else.

**Comment by jojobear13** [comment]
With regards to the viridian karate guy, I don’t think the issue is his line of sight. I think the two stop-tiles below him are backwards.

**Comment by wisp92** [comment]
![Pokemon - Red Version (UE) Shin + Can-Learnset -0](https://user-images.githubusercontent.com/21172590/129283674-8dedfd94-2b76-4683-a68f-d32ab5aaeee1.png)

**Comment by wisp92** [comment]
Are we referring to the same guy? If so can you explain what do you mean by backward so I can check other tiles as well?

**Comment by jojobear13** [comment]
> 
> 
> Are we referring to the same guy? If so can you explain what do you mean by backward so I can check other tiles as well?

That's the guy. Below him are two stop tiles. One at upper-left and another at lower right.

In vanilla, it does not matter which tile you stop on. You can always sneak past his sight.

If his sight is increased to 3 spaces, then it still doesn't matter which tile you stop on. You cannot sneak past his sight at all.

But now rearrange the stop-tiles so that one is now at upper-right and one is at lower left.
<img width="142" alt="Untitled" src="https://user-images.githubusercontent.com/47074297/129288256-1ff17199-0249-448e-b802-df05673b6b49.png">

Stopping on the left tiles lets the player sneak around, but stopping on the right tile gets the player an unexpected battle. The player's choice of spinner now matters.

**Comment by wisp92** [comment]
Noted, I'll keep it in mind for the next playthrough. Although, I don't think there are many other similar situations in the game. In the Rocket's Hideout, the trainers and the puzzles lie mostly in different parts of the map.
