### ISSUE TITLE
Clarify Giovanni's line about losing to you

### ISSUE THREAD

**Issue by jojobear13** [jojobear13/shinpokered#159]
Giovanni, after giving you the earth badge, says "Having lost, I cannot face my underlings!" as the reason he disappears. This can be misinterpreted as him leaving because he was beaten in his gym by a child, yet the Rival would have had to defeat him to get to the pokemon league. Doesn't really jive.

Instead, adjust the line a little bit:
"Having lost to you yet again, I cannot face my underlings!"

**Comment by GLSWV** [comment]
Alternatively, the FireRed/LeafGreen revision of the dialogue could be used:

"Having lost in this fashion, I can't face my followers."

Or just the first part of the sentence.
