### ISSUE TITLE
Wrap + Sleep = Poison Bug (Difficult to Replicate)

### ISSUE THREAD

**Issue by wisp92** [jojobear13/shinpokered#16]
It only happened once so far, so I suspect the conditions to replicate it are difficult. I will describe the battle in hope to provide some insight:

Me: Hypnosis -> Didn't Effect
Opponent: Wrap -> Missed
Me: Hypnosis -> Didn't Effect
Opponent: Wrap -> Hits (1-2 turns but I can't remember exactly)
Me: Hypnosis -> Hits

Result:
Opponent: Poisoned
Me: Wrapped

Theory: I suspect the opponent was going to use PoisonPowder, but the effect got applied to itself.

**Comment by jojobear13** [comment]
Who had the higher speed? Were you able to use Hypnosis despite being hit with wrap?

**Comment by wisp92** [comment]
I had the greater speed.

Update: It just happened again but no wrap was used this time.

Battle with Fisherman in Route 12:
Defeated Goldeen (First PKMN) using Hypno
He sent out Shelder.
I used Hypnosis and the opponent was Poisoned.

Shelder doesn't have a poisoning attack; hence, I believe that it's related to the move now.

**Comment by wisp92** [comment]
It just happened again but I just realized I missing the latest commit. I saw that you updated the counter again, maybe that solves it.
