### ISSUE TITLE
an extra rival object is spawning during the 2nd route 22 battle

### ISSUE THREAD

**Issue by jojobear13** [jojobear13/shinpokered#161]
https://youtu.be/3gFhr-OXoY8?t=1362

**Comment by wisp92** [comment]
Since I quite recently went through this spot, I can confirm that it didn't happen with a male character and on foot in mGBA.

**Comment by jojobear13** [comment]
This happens when the first route 22 battle is skipped. It needs to manually be reset after beating brock, and that includes hiding the object.
