### ISSUE TITLE
Minor Bugs & Suggestions - Part 3

### ISSUE THREAD

**Issue by wisp92** [jojobear13/shinpokered#166]
Hope these help. I am trying to find more.

Game Bugs:
1. The sealed area in PKMN tower allows for PKMN encounters. This contradicts the channelers description of the area who states that it is a safe zone.
2. Saffron City should come before Cinnabar Island and Victory Road on the map and flying options. Intuitively the order should follow the badge order I believe.

Meta-Game Bugs:
3. In the Safari meta-Game it is possible to encounter Lapras in the grass area; not sure about other sea-PKMN.
4. Selling PKMN in Celadon City doesn't reset the PKMN pointer in the relative Menu.
5. The price of the PKMN is buggy in the Celadon City PKMN buyer. Specifically, selling a rare Lapras with good DVIs set the price above 30,000. Selling any common PKMN, e.g., Nidoran, only changed the lower digits of the price. Seems like the higher digits do not update correctly in such cases.

Text:
6. The man from who TM 28 (Dig) was stolen reverts back to his original text if the player does not possess the TM 28 anymore. Reading both texts I believe this behavior was not intended so maybe a flag could be set based on acquiring the TM to prevent this.
7. The trainer in the top-left corner in the maze of Route 14 says that PKMN can't forget HM moves; in the Master build he should say something like PKMN can't forget HM moves without help.
8. The channeler in PMN Tower 5F says post-battle: "Hair didn't fall out! It was an evil spirit!" This is probably some direct translation from Japanese but maybe there is a better translation since this one sounds weird in English. Unfortunately, I don't know Japnese to help more with that.

Suggestions:
9. Pressing (B) in Safari Zone PKMN encounters could move the pointer to the Run option.
10. Post Elite Four, instead of buying fossils from the Celadon Department Store, Slowpoke (the warden of Safari Zone) could sell them to the player for a good price (maybe to fix his teeth). It is mentioned in the folklore that he possesses rare PKMN fossils.

**Comment by jojobear13** [comment]
1 - This is not a bug. All walking tiles in a map use the same encounter table.
2 - I'm not going to mess with this. I've looked into it before, and the order is based on the values of the map constants.
3 - I assume you mean the special event that can be activated in the post-game via the extra gate npc. This is intended. The Safari Zone "special event" was born out of seeing if I could dynamically change random encounters. Pokemon encountered within the safari zone under this event flag will have minimum 9,8,8,8 DVs, and there is a random chance to encounter any non-legendary pokemon. It's just a time-waster I threw together to make the safari zone have a point after catching its unique 'mons.
4 - No biggie. I just need to zero-out wPartyAndBillsPCSavedMenuItem upon confirming the sale.
5 - I'm currently checking some other broken stuff with this. I think I'm misunderstanding how the BCD adder function works.
6 - This is intended. It's a rare bit of roleplaying where the game assumes the player is giving the TM back to the robbed man, and instead plays a special bit of dialogue letting the player know its okay to keep it.
7 - Noted.
8 - This is a reference to https://en.wikipedia.org/wiki/Yotsuya_Kaidan. It makes sense if you've seen one of the many film adaptations.
9 - Keeping this one in the Idea Box. Safari encounters are built over the regular core battle engine. There's no good way to do this without some annoying re-writes and I'm crunched for rom space in that memory bank.
10 - A neat idea, but unfortunately shops are hard-coded to the mart-guy npc. I don't know yet how to change this.

**Comment by wisp92** [comment]
An update about (5), it seems to reset on its own after some sales.
About (1), can't some tiles be treated as road tiles?
About (9), you could change it globally actually. I think Gen-2 (or 3) and above, pressing (B) actually goes to Run option. I need to check it though to make sure.
About (10), if you figure it out there is an employ is Silph Co. that complains the Master Ball project is cancelled he could sell the Master Balls as in a small black market thing. Not sure yet about Moon Stones, but I'll post it if I come across a good spot.
