### ISSUE TITLE
AI - Sleep Move Selection

### ISSUE THREAD

**Issue by wisp92** [jojobear13/shinpokered#168]
Does AI decide whether to use a sleeping move after the player's turn even if the player moves first? I noticed that the opponent keeps using a sleeping move even if at the beginning of the turn the player's PKMN is asleep and the player used the poke flute. This ends in a boring situation where the opponent keeps using the sleeping move and the player keeps using the poke flute until the opponent changes move after about 5 or 6 turns.

Edit: If the opponent has the upper hand in speed a clearly better choice is a sleeping move followed by an attacking move followed by a sleeping move. If the opponent is slower he still shouldn't use a sleeping move on a sleeping opponent except if a PKMN change can be predicted which I am not sure if it falls in the AI layers scope you are planning.

**Comment by jojobear13** [comment]
Gen 1's AI handling is hardcoded such that it is omniscient; it runs after the player has selected an action. Furthermore, there is a quirk where the effects of using an item are applied before the enemy selects a move.

While sleeping moves are not preferenced per se, they are frequently selected via process of elimination as other move options are ruled out.

I could check the results of wActionResultOrTookBattleTurn, which gets set with item usage and switching, and use that to blind the AI a bit.
