### ISSUE TITLE
Use Fly and not Dig in Viridian Forest 

### ISSUE THREAD

**Issue by wisp92** [jojobear13/shinpokered#169]
I suppose the Viridian Forest is considered a cave by the game for simplicity but honestly, I think the player should be able to use Fly and not Dig there. Just a suggestion in case it's an easy fix.

**Comment by jojobear13** [comment]
easy fix

**Comment by jojobear13** [comment]
This has some idiosyncrasies that need to be investigated further.

**Comment by jojobear13** [comment]
did a workaround for now
