### ISSUE TITLE
A Couple of Glitches (Lite Branch)

### ISSUE THREAD

**Issue by wisp92** [jojobear13/shinpokered#17]
Both glitches appear only in the Lite branch(freshly built) and not in the master branch. I included screenshots.

Bug1: In the hotel in Celadon City there is a man who behaves like a nurse from the Pokemon Center (Leftover from Master?)

Glitch1: On the second floor of the Department Store in Celadon City, interacting with the top-left console creates the glitch.

![PokeBlue_Lite_Glitch1](https://user-images.githubusercontent.com/21172590/83633297-4efb5c80-a5d3-11ea-97e4-5aa130f801eb.PNG)
![PokeBlue_Lite_Bug1](https://user-images.githubusercontent.com/21172590/83633301-515db680-a5d3-11ea-88ae-c8e66af823da.PNG)

**Comment by jojobear13** [comment]
latest commit should fix this
