### ISSUE TITLE
AI: Discourage consecutive switches

### ISSUE THREAD

**Issue by wisp92** [jojobear13/shinpokered#172]
It seems AI decides on consecutive switches even for non-jugglers. Specifically, it happened with the random trainer fights in the underground path (both when impersonating Misty and the Rival, who I suppose use all AI layers). The opponent switched PKMN after the previous one fainted and then switched again in the following turn. Is the switch after KO blind to type match-ups?

**Comment by wisp92** [comment]
Update: It might be a coincidence but I think some trainers including Mr. Fuji choose to switch to Rock/Water-type and Rock/Flying-type PKMN against an Electric-type. This is a bad match-up that might have been missed since there are only a few PKMN with these types.

**Comment by jojobear13** [comment]
The switching AI is blind to direct type comparisons. Instead, it scans through all the moves of the player's active pokemon and scores them based on effectiveness. No effect is a score of +15 and any super-effective is -[1/8th move power]. The lowest score is applied to the overall score for switch-in potential.

Possibilities for improvement include:
- score super effective moves as -[1/4th power]
- add an additional score penalty for a direct type disadvantage (potential for STAB)
