### ISSUE TITLE
Jump Kick and Hi Jump Kick inflict itself zero damage when missed

### ISSUE THREAD

**Issue by McPauI** [jojobear13/shinpokered#175]
When you miss Jump Kick and Hi Jump Kick you get zero recoil damage.

**Comment by jojobear13** [comment]
Make the following change under PrintMoveFailureText:

`	;ld hl, wDamage ; since the move missed, wDamage will always contain 0 at this point.
	                ; Thus, recoil damage will always be equal to 1
	                ; even if it was intended to be potential damage/8.
	ld hl, wUnusedD71F ;joenote - threatened damage now gets put in this address on a miss.
						;This should fix the issue with the proper recoil damage
	ld a, [hli]
	ld b, [hl]
	srl a
	rr b
	srl a
	rr b
	srl a
	rr b
	ld hl, wDamage+1  ;<<<<<add this line here after doing the shifts and rolls
	ld [hl], b
	dec hl
	ld [hli], a
	or b
	jr nz, .applyRecoil
	inc a
	ld [hl], a
.applyRecoil`
