### ISSUE TITLE
Exp.Share: 0XP After Opponent Selfdestructs

### ISSUE THREAD

**Issue by wisp92** [jojobear13/shinpokered#19]
EDIT: Tested in Lite Branch
If first PKMN faints due to opponent using Selfdestruct or Explosion the Exp.Share gives 0 xp to the rest of the team. According to Prof. Oak assistant's description, Exp.Share should give xp regardless. If at least another PKMN was send out in the battle the sharing takes place as intended.

**Comment by jojobear13** [comment]
Fainted pokemon don't get exp. I think what's happening is that the battle participants are getting their exp calculated first then the party gets exp based on that. If your only battle participant has fainted, then it thinks there is zero exp. Will look into this later.

**Comment by wisp92** [comment]
Thanks for the reply. I'll also check it send a pull request if a figure it out.

**Comment by wisp92** [comment]
Update: The problem seems to be more general. Exp.Share is applied until the first PKMN with 0 HP. I believe the participant's list is either truncated there or a 0 check takes precedence and exits the loop. 

Tested in Lite Branch.

**Comment by wisp92** [comment]
This a very peculiar bug. After extensive testing the PKMN that do not get XP are the ones in the position of the fainted ones if you count in reverse order. Example: If PKMN #1 is fainted, PKMN #6 does not get Exp.Share XP

**Comment by jojobear13** [comment]
leaving this open for the moment. I'll do some extensive play-testing when I get some downtime from work.

**Comment by wisp92** [comment]
> 
> 
> leaving this open for the moment. I'll do some extensive play-testing when I get some downtime from work.

I am going through Lite Blue in my spare time. So I'll keep you posted.
