### ISSUE TITLE
Color Correction not being applied

### ISSUE THREAD

**Issue by seajaysec** [jojobear13/shinpokered#201]
There doesn't seem to be any visual indicator telling the user if color correction mode is activated, but in gameplay there doesn't seem to be any change after pressing Select at the copyright screen when using a backlit GBC.

**Comment by jojobear13** [comment]
Need more details. What are you playing on?

**Comment by jojobear13** [comment]
Here's a before & after video of how it's supposed to work. This is Shin Red - Master using BGB emulator in GBC mode.

https://user-images.githubusercontent.com/47074297/156942797-04084765-0abb-4bbc-9025-2ccd917cb9b3.mp4

**Comment by seajaysec** [comment]
Thank you so much for the demo video - I was pressing it at the wrong spot for and holding for too long. Works great now that I know where/when to do it.

Is there a flag when building the IPS that would allow for this to be the default palette?

**Comment by jojobear13** [comment]
From the Guide to New Player Functions:

> Changing the destination code of the rom header to 00 (JP) defaults this to ON and pressing SELECT turns it OFF. Use Gameboy Rom Analyzer to change the destination code (https://www.romhacking.net/utilities/1343/).

And from the Additions section of the readme:
>Alternately, remove the 'j' in 'cjsv' in the Makefile to compile with a JP destination code
