### ISSUE TITLE
Trainers using over level 100 Pokémon.

### ISSUE THREAD

**Issue by JOBOalthor** [jojobear13/shinpokered#202]
I battled a trainer I had previously missed while having a level 100 in my party. The trainers Pokémon were level 103. I had the scaling toggle on,and I believe the lower level mons gain more experience toggled on. I assume this isn't intentional! I tried to rematch them immediately after and the levels were reverted back to 100. 

I'm playing on Red Original back v1.23.04

**Comment by jojobear13** [comment]
It's intentional. Keeps the players on their toes. There's also a little training secret associated with it.
<details>
  <summary>spoilers</summary>
  defeating a pokemon over level 100 grants 255 stat exp to every stat
</details>
