### ISSUE TITLE
Adjust text spacing and trainer moves

### ISSUE THREAD

**Issue by JOBOalthor** [jojobear13/shinpokered#203]
When pressing select to use strength the colour of the screen briefly distorts during the pokemons cry. In my case it was a field move on Chansey. Happens in caves as well as town. 

Unrelated, but I noticed at the end of the Mr.Fuji battle it says "Gentleman was defeated" rather than his name, green also says "Jr. Trainer". The Red mind battle says "Jr. Trainer". The Silph Chief correctly says "Chief" though. 

Also the after battle text from beating Green at the docks has text overlapping the border of the text box. 

Oak's Arcanine knows ember and flamethrower and took it easy on me by using ember over and over and then finally flamethrower. 

v1.23.04

**Comment by jojobear13** [comment]
Gen 1 does not support trainers having individual names. Only their trainer class gets printed. The unique trainers, like the gym leaders, are coded as their own separate trainer classes.

The Strength hot-key was given an audio/visual indicator to signal that it had been used. Previously there was no indicator and it was causing player confusion.

I’ll check out those last two.

**Comment by JOBOalthor** [comment]
Thank you for the clarification regarding the trainers! I'm always learning new things about these old games.

**Comment by Mord5** [comment]
![Screenshot_20220822-000732_Lemuroid](https://user-images.githubusercontent.com/52078365/197647731-0e58492b-c688-4224-a13d-7454a766623b.jpg)

I caught a screenshot of the text overlap issue with the Green battle - seems the bug is resolved now, but for the record.
