### ISSUE TITLE
Doesn't get past gender page

### ISSUE THREAD

**Issue by chris1899** [jojobear13/shinpokered#205]
Shin Red loads up fine with the menu and version number. When asking if 'Are you a girl?' I can select Yes/No but cannot proceed to next page.

**Comment by jojobear13** [comment]
Need more details. Which version number? To which base rom was the patch applied? What emulator/hardware is being used for play?

**Comment by jojobear13** [comment]
I attached a video where I patch shin red and shin red lite over a US red rom in order to verify that this works correctly.

https://user-images.githubusercontent.com/47074297/159631027-cc6ed566-55c7-4a62-9850-64f85b27f98d.mp4
