### ISSUE TITLE
Read this before making a bug report

### ISSUE THREAD

**Issue by jojobear13** [jojobear13/shinpokered#206]
Please include all of the following information when you create an issue for a bug report:

- Patch you are using
- Base rom to which you applied the patch
- Version number from the main screen
- Emulator and/or hardware you are using

Your bug report should contain enough detail that the problem could feasibly be replicated. Attaching your .sav file or a BGB save state file is also helpful (but not required).

**Comment by coltongit** [comment]
An issue template could work around this issue by showing this before every issue ticket opened (similar to how upstream's will likely be, see https://github.com/pret/pokecrystal/pull/974 and https://github.com/pret/pokecrystal/issues/930)

**Comment by jojobear13** [comment]
Templates for suggestions and bug reports are in effect.
