### ISSUE TITLE
Possibly add VC compatibility? (Notes to self)

### ISSUE THREAD

**Issue by jojobear13** [jojobear13/shinpokered#207]
reference https://github.com/pret/pokered/pull/351

**Comment by vulcandth** [comment]
Is this a question, request, or something else? I see you referenced my in-progress PR.

**Comment by jojobear13** [comment]
More info at https://github.com/pret/pokecrystal/blob/master/docs/vc_patch.md

**Comment by jojobear13** [comment]
Not worth doing anymore since the Virtual Console has been deprecated.
