### ISSUE TITLE
Spaceworld back-sprites not appearing on Shin Green

### ISSUE THREAD

**Issue by vaguesuper64** [jojobear13/shinpokered#208]
Using: Shin Green 1.23.05
Screen version: 1.23.05M
ROM: Pokemon Blue US 1.0
Emu: My OldBoy (Android)

Every other feature appears fine, but the game is using standard back-sprites instead of the Spaceworld back-sprites.
(This may be intentional for this patch, but I didn't see it anywhere in the notes.)

**Comment by jojobear13** [comment]
Only the default red/blue patches use the larger back sprites as of 1.23. The next version will make it easier to edit the makefile and main.asm so that a user may compile with the sprite set desired.
