### ISSUE TITLE
Supper Effective Message for Seismic Toss and Night Shade

### ISSUE THREAD

**Issue by wisp92** [jojobear13/shinpokered#21]
Tested in both Master and Lite Branches.

Supper Effective message appears for Seismic Toss and Night Shade (respecting type match-ups). Both of them however inflict set damage (based on PKMNs level) which is applied correctly.

Can't verify at the moment if the message appears for Dragon Rage as well (It might or might not since this move is unaffected by PKMN level)

**Comment by jojobear13** [comment]
Fixed in master via 3de1e19204198a47447ce8b4ade079cf05de79ff. Need to migrate this over to Lite branch.
