### ISSUE TITLE
Viridian Forest 2x2 block encounter glitch not fixed

### ISSUE THREAD

**Issue by Mord5** [jojobear13/shinpokered#210]
The [Viridian Forest no encounter grass tiles glitch](https://glitchcity.wiki/Viridian_Forest_no_encounter_grass_tiles_glitch) is still in effect. (ROM built from https://github.com/jojobear13/shinpokered/commit/cc28c3da068a883bdfe37406eb6251d467cc40e9.)

https://github.com/jojobear13/shinpokered/blob/cc28c3da068a883bdfe37406eb6251d467cc40e9/engine/battle/wild_encounters.asm#L28

Is this behavior intentional in shinpokered?

**Comment by jojobear13** [comment]
Somehow that file got reverted. Fixed in 363cb6ea0a44b7582b046d74c3b560ce45313130. Slated for next release.

**Comment by jojobear13** [comment]
Going with this 237539e3d9ae172ddb43039f2c48b3f98fd8ba29 as a solution. More elegant, takes up less space, and harder to mess something up with a typo. I suspect that Gamefreak waffled back and forth on which tile (bottom left or right) was supposed to be used for encounters. Settling on bottom-left is probably what should have been done.
