### ISSUE TITLE
Request: Increment HP when leveling up using EXP ALL

### ISSUE THREAD

**Issue by RomanADavis** [jojobear13/shinpokered#212]
In Pokemon, when you level up and again HP, that HP is usually filled up, but not when leveling up using EXP ALL; It would be nice if it also incremented when your pokemon levelled up using EXP gained from EXP ALL.

**Comment by jojobear13** [comment]
Request unclear. Template format not followed. A quick experiment shows that the presence of exp all does not effect the amount of HP restored to a pokemon that levels-up in battle. HP gets restored such that (old HP / old maxHP) ~= (new HP / new maxHP). This is the intended behavior for gen-1 games.
