### ISSUE TITLE
Small suggestion: Add Counter out of Critical Hit moves

### ISSUE THREAD

**Issue by McPauI** [jojobear13/shinpokered#216]
Heyo! I really love your work and use it to study the decomps of Red and Blue.

Here's a suggestion. I noticed Counter could still crit despite having "fixed" damage. You could just add two lines:

	cp COUNTER
	ret z

To Critical hit excuclusion code, just below SPECIAL_DAMAGE_EFFECT to prevent this in core.asm.

Have a nice day, seeya!

**Comment by jojobear13** [comment]
Note to self: instead of checking for SPECIAL_DAMAGE_EFFECT, check for a base power of 1 which shinpokered assigns to all moves that do fixed damage (includes bide, super fang, OHKO moves, etc).

**Comment by jojobear13** [comment]
resolved in commit 0b3b20d9bdfb7f0c1273ce1e0bbf901e8dd50afc
