### ISSUE TITLE
Request: Convert Disassembly Format To Pokegold 

### ISSUE THREAD

**Issue by GBC-OG** [jojobear13/shinpokered#221]
Is there any chance this disassembly for Shinpokered could be converted into the Pokegold/Pokecrystal format? It would make it A LOT easier to edit things like trainer party movesets. For example, JustRegularLuna has a "clean" disassembly of vanilla pokered that does this: https://github.com/JustRegularLuna/pokered-clean

Could this be done with Shinpokered? It would be nice to have Shinpokered as a code base for all the AI improvements and Bug Fixes with greater flexibility for editing trainer movesets.

**Comment by jojobear13** [comment]
This would be a massive undertaking. Unfortunately, the shinpokered crew is getting older and can't really commit to this.
