### ISSUE TITLE
Bug: Minor text issues

### ISSUE THREAD

**Issue by Mord5** [jojobear13/shinpokered#225]
**What emulator and/or hardware are you are using?**
Lemuroid for Android

**What version of this project are you using?**
v1.23M, built from source commit https://github.com/jojobear13/shinpokered/commit/cc28c3da068a883bdfe37406eb6251d467cc40e9

**What is the problem you encountered?**
During the Team Rocket takeover, the female Silph Co worker on 10F has weird text spacing in her dialog box `_SilphCo10Text_5a1d3`:
![Screenshot_20220808-110853_Lemuroid](https://user-images.githubusercontent.com/52078365/197650567-c9bdda2d-f5b5-4d74-99aa-887fda263918.jpg)

The Trainer Tips sign in Celadon City `_CeladonCityText16` has false info about what "Guard Spec." does:
```
	para "GUARD SPEC."
	line "protects #MON"
	cont "against SPECIAL"
	cont "attacks such as"
	cont "fire and water!"
```
It should say somthing like
```
	para "GUARD SPEC."
	line "protects #MON"
	cont "against moves"
	cont "like GROWL and"
	cont "TAIL WHIP!"
```

**Comment by jojobear13** [comment]
fixed in 73f9a7d2

**Comment by Mord5** [comment]
Found one more - the male shopper on 2F of Celadon Dept Store says Super Repel is a "more powerful" Repel, which is misleading. He should probably say it's a "longer lasting" Repel.

**Comment by Mord5** [comment]
https://github.com/jojobear13/shinpokered/blob/f94279d8763abcabcd7c80db2b4635222c9a16db/text/maps/vermilion_dock.asm#L76
Typo - should be "locator"
