### ISSUE TITLE
Request: Poke Mart item QOLs

### ISSUE THREAD

**Issue by Mord5** [jojobear13/shinpokered#228]
**Describe the feature you would like**
There are a few items missing from certain Poke Marts that could improve the early game experience:

Viridian Mart: Add Potion _(& change `_ViridianMartText3` to reflect this change)_
- Potions are available in Pewter City, so their being unavailable in Viridian only prevents the player from having spare Potions on hand for the one unavoidable Bug Catcher fight in Viridian Forest. Adding Potions to Viridian just eliminates a lot of tedious and unnecessary back-and-forth.

Pewter (& possibly also Viridian) Mart: Add Repel
- I don't think the play experience is much improved by mandatory bat and bug swarms in Mt. Moon/Viridian Forest. There's an argument to be made that it forces the player to train since you can't run if your mon is too slow, but eh. I just don't enjoy dealing with the Zubat horde.

At some point, maybe as late as the postgame shop: Add Max Revive
- Up to you if you think making these available before the E4 will dilute the difficulty on shift/easy mode, but if you're playing on set/hard mode you can't use them in battle anyway so it's just a post-battle convenience.

**Comment by jojobear13** [comment]
For now, will add max revives to the post-game celadon mart.
