### ISSUE TITLE
Bug: Enemy HP bar colors don't immediately reset after heal

### ISSUE THREAD

**Issue by Mord5** [jojobear13/shinpokered#229]
**What emulator and/or hardware are you are using?**
Lemuroid for Android

**What version of this project are you using?**
v1.23M built from source commit https://github.com/jojobear13/shinpokered/commit/cc28c3da068a883bdfe37406eb6251d467cc40e9

**What is the problem you encountered?**
When an enemy mon's HP is reduced so as to change the color of its HP bar from green to orange/red, and is then healed back into green range, the color of its HP bar remains orange/red until after the player action completes (assuming the player action goes after the enemy item use, i.e. player used a move, not an item or switch).

**Expected behavior**
The color of the bar HP should reset immediately after the HP bar movement animation concludes (this is how it behaves for player mons).

**Is it possible to reproduce the problem?**
This should apply to all trainers, but I've found this issue is pretty easy to replicate while battling Lorelei.

**Screenshots/Video**
https://user-images.githubusercontent.com/52078365/204168269-fe75f73d-4774-421e-8a93-8f750aadc9eb.mp4

**Comment by jojobear13** [comment]
Got it. I have documented this bug and its fix over on the pokered wiki.

https://github.com/pret/pokered/wiki/Bugs-and-Glitches#ai-trainer-hud-does-not-update-when-it-uses-healing-items
