### ISSUE TITLE
Unable to compile clean ROM of shinpokered lite

### ISSUE THREAD

**Issue by skibalovesya** [jojobear13/shinpokered#230]
I feel a bit silly submitting this as an issue as it could be something I'm doing wrong, but here is the error I get when I try to compile:

error: audio.asm(6) -> constants.asm(9) -> constants/misc_constants.asm(35):
    syntax error, unexpected set
error: audio.asm(6) -> constants.asm(9) -> constants/misc_constants.asm(36) -> macros/data_macros.asm::const(8):
    Expected constant expression: 'const_value' is not constant at assembly time
error: audio.asm(6) -> constants.asm(9) -> constants/misc_constants.asm(36) -> macros/data_macros.asm::const(9):
    Expected constant expression: 'const_value' is not constant at assembly time

The lines in question are as follows.
misc_constants 35 and 36:
const_value set 0
	const BIT_A_BUTTON

I have not edited any of the files in question. I just cloned the lite branch and typed make.

**Comment by jojobear13** [comment]
Type ` rgbasm --version`. Make sure you are running rgbasm v0.5.2

**Comment by jojobear13** [comment]
also, type `git status` and paste the report it gives you

**Comment by jojobear13** [comment]
Closed. Problem was solved by downgrading to a compatible rgbasm version.
