### ISSUE TITLE
Trainer Escape Glitch

### ISSUE THREAD

**Issue by DiabloStorm** [jojobear13/shinpokered#236]
>That graphical glitch is caused by an invalid address jump somewhere. I think I fixed that already. I've tried to close as many holes and escape glitches as I can, but once in a while a new one gets discovered.

_Originally posted by @jojobear13 in https://github.com/jojobear13/shinpokered/issues/234#issuecomment-1365628890_

[Not fixed](https://www.youtube.com/watch?v=gw2S5p01ksM)

You can do variations on this, like instead of talking to the old man (the dialogue box seems to enter an infinite loop)

Instead of talking to the old man, just go back to the area the trainer is in, the original trainer battles you as soon as you step into the area, forfeit the battle and the screen goes white with a bunch of crazy sounds, eventually the game comes back and you get another battle at your spawn point from the same trainer.

Reproduce: Just get into a wild battle (and lose) that happens to be on the square in front of a trainer.

**Comment by jojobear13** [comment]
plugged-up being able to black out from a wild battle to escape from being spotted in commit 512e29ff5384d39026662d7f159889ef8ee861e4
