### ISSUE TITLE
Bug/Oversight: Rock Slide's description says it can flinch, but Rock Slide was not updated to cause flinch

### ISSUE THREAD

**Issue by skibalovesya** [jojobear13/shinpokered#237]
I don't know which direction you'd prefer to take it, but when you give the girl in Celadon Soda Pop, and she gives you the Rock Slide TM, she states that it can spook the target sometimes. However, Rock Slide's effect was never updated to reflect this comment.

**Comment by jojobear13** [comment]
I'll have to have an internal fight about this one. It's going to come down to teasing out what the original intent was with the move. There's good evidence over on TRCF (https://tcrf.net/Development:Pok%C3%A9mon_Red_and_Blue/Miscellaneous_Data) that Rock Slide was shifted around and replaced a completely different scrapped move.

**Comment by jojobear13** [comment]
So it is unlikely that this line of text refers to flinching, and that Rock Slide having a flinch effect was not considered until gen-2.

Some really old japanese web pages have been dug up concerning this text error, and even they are confused. The operative word used to describe the TM's effect is "kizetsu" meaning "to faint/swoon/pass out". Neither Gen 1 or Gen 2 ever use "kizetsu" with respect to flinching. The word itself explicitly denotes a loss of consciousness with its kanji meaning "to cut off the spirit". Furthermore, while english uses "faint" as the term for hitting 0 HP, the japanese script calls this being "out of energy/power" and does not use the word "kizetsu" (0-HP pokemon are explicitly conscious in the japanese red/green games).

If even old japanese fans are scratching their heads, then it's not a matter of localization. Script translator Nob Ogasawara chose to localize this text as "spooked" probably with regard to passing-out from fright or shock. Sleep is the only effect that denotes a loss of consciousness, but what the actual effect was is something that seems lost to time. 

Rock Slide did replace a scrapped move called Star Freeze which would have been associated with Starmie. This move made its way into the initial release of the Trading Card Game (developed in-tandem with the gen 1 games). It likely had a freezing side effect. Rock slide itself was a kind of less-powerful Earthquake during development with the ground typing and no additional effect. If the rooftop girl did give out Star Freeze at some point, then Ice Beam is what probably filled-in its omission.

To further muddle things, the Tri-Attack TM had a line from this girl NPC that was only in japanese red & green that states it can sometimes cause paralysis. Did tri-attack originally have an effect? No, it did not. Concept art and development stats do not support this and indicate that it's supposed to be a neutral energy triangle hurled at the target (gen 2 would change this concept). Tri-attack probably replaced another move that was once there. Good candidates might be the deleted moves 500,000 Volts (a stronger thunderbolt) or Paralyzing Scissors.

So all that can really be inferred from this is that the rooftop girl was originally supposed to give TMs that had major side-effects as their theme: freeze, paralysis, and one having to do with passing out. But over time the moves got shuffled around and reworked. Whatever theme she had going on was lost, but the text never got proper corrections in the initial release of the games.
