### ISSUE TITLE
Graphical glitch when healing 6 pokemon

### ISSUE THREAD

**Issue by DiabloStorm** [jojobear13/shinpokered#238]
[Video](https://www.youtube.com/watch?v=UWTDv7TXhlM)

![image](https://user-images.githubusercontent.com/63818362/210169725-5ec7cd56-e691-4749-b003-d3d8d32d37ae.png)

**Comment by jojobear13** [comment]
fixed in commit 7a2fe0112aef36cc5c2766d79ce7dff9800f38d1
