### ISSUE TITLE
trouble building lite on macOS

### ISSUE THREAD

**Issue by altbanty** [jojobear13/shinpokered#240]
I've run into a issue trying build the lite branch. the original powered repo builds fine for me though.

My assembler knowledge is not great. Any ideas what may be off?

error: audio.asm(6) -> constants.asm(9) -> constants/misc_constants.asm(35):
    syntax error, unexpected set
error: audio.asm(6) -> constants.asm(9) -> constants/misc_constants.asm(36) -> macros/data_macros.asm::const(8):
    Expected constant expression: 'const_value' is not constant at assembly time
error: audio.asm(6) -> constants.asm(9) -> constants/misc_constants.asm(36) -> macros/data_macros.asm::const(9):
    Expected constant expression: 'const_value' is not constant at assembly time

**Comment by jojobear13** [comment]
You might have to use rgbasm 0.5.2 to compile the regular lite branch. The lite_dev branch has been updated to use rgbasm 0.6.0.

I've found that constantly switching my global rgbasm version to be annoying. Fortunately the pokered folks have instructions to compile with a project-specific version: https://github.com/pret/pokered/blob/master/INSTALL.md#build-with-a-local-rgbds-version
