### ISSUE TITLE
Question: ai_pointers.asm ?

### ISSUE THREAD

**Issue by JagobaRiscado** [jojobear13/shinpokered#241]
Hello, I'm new with Red/Blue hacking, I'm making first a simple hack, and even though it's impressive how many things have been fixed, I'm only interested in the improved trainer AI (might review the changes and think about using everything). I found the trainer_ai.asm file, but I can't find the ai_pointers.asm one. I guess the AI assignment file is somewhere else, and that's what I want to ask: which file it is? Or in case I get more questions than answers: How can I implement only the improved triner AI?
Thanks.

**Comment by jojobear13** [comment]
Shinpokered was forked from pokered a few years ago, so quite a few things are organized differently.

You are probably looking for this: https://github.com/jojobear13/shinpokered/blob/f94279d8763abcabcd7c80db2b4635222c9a16db/engine/battle/trainer_ai.asm#L1454
