### ISSUE TITLE
"I think one could could be in here."

### ISSUE THREAD

**Issue by DiabloStorm** [jojobear13/shinpokered#249]
![image](https://user-images.githubusercontent.com/63818362/213516081-6e17aa6a-221b-4845-be93-36fc12248bf5.png)

**Comment by jojobear13** [comment]
Reword?

**Comment by DiabloStorm** [comment]
It's a grammatical error/oversight.
ex:
https://i.stack.imgur.com/aS9YV.png

**Comment by jojobear13** [comment]
I had to read it a couple times before my brain caught on.
mind = blown.

**Comment by DiabloStorm** [comment]
> I had to read it a couple times before my brain caught on. mind = blown.

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3543826/ apparently it's a thing that happens

**Comment by jojobear13** [comment]
Fixed in 4b72e8be62ab6a7f615cef89362e6a84a1460055
