### ISSUE TITLE
Make missingno encounter *rate* actually reasonable

### ISSUE THREAD

**Issue by DiabloStorm** [jojobear13/shinpokered#250]
[This ain't it, chief.](https://www.youtube.com/watch?v=bkdtseMZFf8)

**Comment by jojobear13** [comment]
note to self. Increase chance of encounter by a factor of 1 power.

**Comment by jojobear13** [comment]
Adjusted in ae6053885b560138517bf1c3b4ac968a707dc697

Now chance of encounter statistically works out to be about 90% after an average of 10 seconds.

**Comment by DiabloStorm** [comment]
I don't know if seafoam island is handled separately but was this applied there? I didn't time that one.

**Comment by jojobear13** [comment]
Yes. The surfing area on both shores are technically on the route 20 map.
