### ISSUE TITLE
To Do: AI improvements to switching

### ISSUE THREAD

**Issue by jojobear13** [jojobear13/shinpokered#26]
The AI for switching is admittedly not super robust. It switches defensively to the next mon in the roster and is blind to the mon it switches to. I’m going to revisit the switching AI and, at the very least, try to prevent it from doing blatantly stupid switch-ins. The master and lite branches will get this one.

**Comment by wisp92** [comment]
Since you are revisiting this, I noticed that sometimes the AI chooses to switch even though it was forced to bring out a new PKMN in the previous turn through KO.

**Comment by jojobear13** [comment]
That's because choosing a new pokemon after a KO is in no way handled by the AI routines. It just loads whatever is next in the opponent's team. AI routines also run after the player picks a move. So sometimes it decides after the fact that its current mon was a bad choice and switches to avoid an incoming super-effective move.

**Comment by jojobear13** [comment]
>Would it be possible to discourage switching to the same PKMN until the player switches too?

I have a few ideas of how I might want to do this. In a general sense, I want to scan through the trainer roster and "score" each non-fainted mon based on various parameters. The mon with the best score gets switched-in. If no other mon has a better score than the current mon, or if all the scores are too low as to be a deal-breaker, then switching is aborted.

**Comment by wisp92** [comment]
Sounds good and challenging (programmatically). I am looking forward to seeing it

**Comment by jojobear13** [comment]
Initial attempt at this has been committed.
