### ISSUE TITLE
Request: HP UP should heal by amount of increase to max HP

### ISSUE THREAD

**Issue by Mord5** [jojobear13/shinpokered#261]
**Is your feature request related to a game-play problem?**
It's annoying that when you use HP UP on a mon with full HP, you end up with a tiny number of missing HP. HP gains from level ups don't behave this way.

**Describe the feature you would like**
It would be convenient for HP UP to heal the target mon by the amount of the increase to its max HP.

**Additional context**
This behavior is already coded for Rare Candies in [ lines 1466-1500 of `items.asm`.](https://github.com/jojobear13/shinpokered/blob/6ba1ffd3a5631f179f3a766a0ed61da1839aff47/engine/items/items.asm#L1466-L1500)

**Comment by jojobear13** [comment]
added in commit 5ead339679d88794f8a424ac90626456488d2bad
