### ISSUE TITLE
Request: Rival item use

### ISSUE THREAD

**Issue by Mord5** [jojobear13/shinpokered#262]
**Describe the feature you would like**
Rival uses Potions on the SS Anne through to Route 22 (2nd). This is pretty weaksauce.

I would like Rival to use Super Potions at Pokémon Tower, Hyper Potions at Silph, and Hyper or Max Potions at Route 22 (2nd).

In general, all Trainers that use healing items could probably stand to use them more often and at higher HP thresholds, especially on Hard Mode. 66% chance of use when <=33% HP seems reasonable to me as a general proposition.

Also, the Champion Rival can't use his Full Restores deliberately to heal status effects, which I think he should be able to do.

**Comment by jojobear13** [comment]
>In general, all Trainers that use healing items could probably stand to use them more often and at higher HP thresholds, especially on Hard Mode. 66% chance of use when <=33% HP seems reasonable to me as a general proposition.

Trust me. You probably don't want this. Some experimenting was done with making item usage more common, and the result is that the AI has a tendency to blow its turn using an item in moments where it really kills the mood. Though creating a new rule tree for more intelligent item-usage is something to keep in the back of my head.

>Also, the Champion Rival can't use his Full Restores deliberately to heal status effects, which I think he should be able to do.

Good idea.

> Rival uses Potions on the SS Anne through to Route 22 (2nd). This is pretty weaksauce.

That's because it uses the Rival2 trainer class for all those battles. 

>I would like Rival to use Super Potions at Pokémon Tower, Hyper Potions at Silph, and Hyper or Max Potions at Route 22 (2nd).

Normally not built into the item-using part of trainer classes, but I'll see what I can do by checking the event flags.

**Comment by Mord5** [comment]
> That's because it uses the Rival2 trainer class for all those battles.
> Normally not built into the item-using part of trainer classes, but I'll see what I can do by checking the event flags.
I was able to trigger this behavior by adding a `wCurMap` check to `Sony2AI` without the need to add a different trainer class, but maybe there's some pitfall I've overlooked.

> Trust me. You probably don't want this. Some experimenting was done with making item usage more common, and the result is that the AI has a tendency to blow its turn using an item in moments where it really kills the mood. Though creating a new rule tree for more intelligent item-usage is something to keep in the back of my head.
Could be. Dealing with Blue's Alakazam with Recover is unpleasant enough as it is that I cut Recover PP to 5 in my home game, so there's definitely something to what you're saying.

Maybe trainers having a # of items per battle rather than per mon would alleviate some of this? But IDK if that would A) actually do anything to fix the problem, B) be practical to implement, and C) be in-scope for the project vision.

Or maybe the problem is me and I just need to learn to stop worrying and love the item clause. 😋

**Comment by jojobear13** [comment]
I think these adjustments might be good to play around with: 65ce57f4217030a42b888ac7221142f9068fc0f4

- Erika has a 50% chance of using a super potion when health is below 1/5th (up from 1/10th): 1 per 'mon
- Blaine has a 50% (up from 12.5%) chance of using a hyper potion when health is below 1/5th (up from 1/10th): 1 per 'mon
- Sabrina has a 50% (up from 12.5%) chance of using a hyper potion when health is below 1/5th (up from 1/10th): 1 per 'mon
- Lorelei has a 50% chance of using a hyper potion when health is below 1/3th (up from 1/5th): 2 per 'mon
- Bruno has a 50% chance of using a hyper potion when health is below 1/3th (up from 1/5th): 2 per 'mon
- Agatha has a 50% chance of using a hyper potion when health is below 1/3th (up from 1/5th): 2 per 'mon
- Lance has a 50% chance of using a hyper potion when health is below 1/3th (up from 1/5th): 2 per 'mon (up from 1)
- Rival3 Champion has 1 full restore per 'mon and has: 
  - a 50% chance (up from 12.5%) to use it when health is below 1/3th (up from 1/5th)
  - a 25% chance to use it to heal a status effect
- Rival2 has a 50% (up from 12.5%) chance of healing if health is below 1/5th: 1 per 'mon
  - Super potion if Pokemon Tower fight has not been beaten
  - Hyper Potion if Pokemon Tower fight has been beaten
