### ISSUE TITLE
I don't think this house in Pewter is supposed to be like this (1.23.13)

### ISSUE THREAD

**Issue by DiabloStorm** [jojobear13/shinpokered#266]
![image](https://user-images.githubusercontent.com/63818362/220274426-fb7d285a-570e-454e-b10e-75b75a4bb994.png)

**Comment by DiabloStorm** [comment]
Another Pewter house

![image](https://user-images.githubusercontent.com/63818362/220274911-609bcd4a-2b59-48fa-a623-3a1ba8ddc425.png)

**Comment by DiabloStorm** [comment]
Cerulean
![image](https://user-images.githubusercontent.com/63818362/220285774-a7696391-01ab-492b-bb6a-c1dab4c839e7.png)

**Comment by jojobear13** [comment]
Looks like the one house map in viridian is reused by a whole bunch of different houses.

I think I fixed it and re-uploaded the v1.23.13 patches.
