### ISSUE TITLE
Request: Try to optimize the lag in cinnabar gym

### ISSUE THREAD

**Issue by jojobear13** [jojobear13/shinpokered#267]
There is a noticeable lag caused when loading the map due to all the wall tiles that have to be replaced. Look into a way to optimize this.

**Comment by Vortyne** [comment]
blocks that are offscreen can be replaced via ReplaceTileBlock without calling RedrawMapView (the slow thing) at the end - they'll be updated when they come on-screen

might be useful to know

**Comment by Vortyne** [comment]
You might also try replacing all the blocks view ReplaceTileBlock - but only calling RedrawMapView once at the end of all the replacements. I've tried this in bills house with every single block being replaced and it seems to take the same amount of time as only replacing one or two.
