### ISSUE TITLE
Incorrect Rival's Position During Encounter on Route 22

### ISSUE THREAD

**Issue by wisp92** [jojobear13/shinpokered#27]
I am copying that here because I wasn't able to resolve it yet.

Tested in Lite Version.

The Rival's position during the cutscene before both battles (after receiving the Pokedex, and after collecting all the badges) seems to be random.

I was able to understand the following so far:
* Script 0 checks whether the events are applicable.
* Scripts 1 to 3 are executed during the first encounter, while scripts 4 to 6 during the second one.
* Script 7 just ends both routines.

Update: The problem is still there even after commenting out the SetSpriteFacingDirectionAndDelay calls. I wonder if it is a result of a random direction applied afterward, e.g. like with battled trainers.

**Comment by jojobear13** [comment]
I'm a little confused. Do you mean the coordinates he appears at is random? Or do you mean the path that he walks is random? Or do you mean his facing is random after stopping next to the player?

**Comment by wisp92** [comment]
The facing. It's a bit random so you can check with save/load,

**Comment by jojobear13** [comment]
It's caused by 0109211a8041b4142cd2ec7766f3a93fbf0ad85e which fixing the amazing man glitch. Object sprites get updated before printing the text box so they kind of look wherever. I'll have to fix amazing men some other way.
