### ISSUE TITLE
Request: Add JP versions based on pocketrgb-en

### ISSUE THREAD

**Issue by malvarenga123** [jojobear13/shinpokered#271]
**Describe the feature you would like**
Considering you already have both the Japanese patches to Red, Blue and Green, it would be interesting to have those versions using the script/names from https://github.com/Dracrius/pocketrgb-en

**Additional context**
That project tries to be more of a literal translation from the Japanese games, so it keeps the Japanese equivalents of Pokemon/People/Cities names.

**Comment by jojobear13** [comment]
I've helped out Dracrius a bit and there is cordiality between us. I don't want to step on his toes.
