### ISSUE TITLE
Bug: Max Revives do not work in battle with Battle Style set to Shift

### ISSUE THREAD

**Issue by Greenknight9000** [jojobear13/shinpokered#279]
**Review the [Compatibility Notes](https://github.com/jojobear13/shinpokered/#compatibility-notes)**
In particular, not all emulators or non-official hardware solutions are supported due to bugs induced from lack of accuracy. Proper bugs should be able to be replicated on official hardware or, to a lesser extent, the latest version of the BGB emulator.

**What emulator and/or hardware are you are using?**
BGB Emulator

**Which patch are you using?**
I assume it's 1.24, despite the Git readme saying Version 1.23.15; I had compiled from the Git Master so I assume that some information hasn't been updated to account for it. The compilation settings I used is:
`$(pokered_obj): 			RGBASMFLAGS += -D _RED -D _ENCRED -D _SWSPRITES -D _SWBACKS -D _FPLAYER -D _MOVENPCS -D _RUNSHOES -D _EXPBAR 
`

**What ROM base are you using?**
Pokémon Red

**How are you utilizing the patch?**
I compiled the ROM myself via Cygwin64

**What version of this project are you using?**
V1.23.15M

**What is the problem you encountered?**
Max Revives do not work during battles; they prompt Professor Oak to say this isn't the time to use that despite Battle Style being set to Shift

**Expected behavior**
The fainted Pokémon is revived from fainting and is restored to maximum health.

**Is it possible to reproduce the problem?**
1. Go into a battle (For this situation I was in Rival Battle 5 in Silph Co.) 
2. Have a Pokémon faint
3. Attempt to use a Max Revive, you should be prompted that you can't do that

**Screenshots/Video**

https://github.com/jojobear13/shinpokered/assets/91160044/5cab7264-e541-43f7-9046-494580676b32

**SAV file or Save States**
Attaching your raw .sav file and/or a BGB save state file is also helpful (but not required).
[pokeredsave.zip](https://github.com/jojobear13/shinpokered/files/12672824/pokeredsave.zip)

**Comment by jojobear13** [comment]
Hard mode has since been decoupled from the battle style. You can tell its active from the exclamation mark on the options screen.
![image](https://github.com/jojobear13/shinpokered/assets/47074297/d3b04fe2-1af7-410c-938b-2db318b15b71)

Pressing RIGHT while the cursor is in the BATTLE STYLE box will toggle hard mode on/off.  
Contrasting this, pressing LEFT will let you select a battle style without toggling difficulty.
