### ISSUE TITLE
Bug: Game hangs and crashes at hall of fame

### ISSUE THREAD

**Issue by jojobear13** [jojobear13/shinpokered#281]
This is a known issue with pre-release downloads of v1.24.0 dated before 9/24/2023. Please re-download and re-patch using 1.24.0 patches from this repository or the patch version 1.24.0b from [RHDN ](https://www.romhacking.net/hacks/8087/). Your save file will not be affected.

**Comment by jz-k** [comment]
This may still be happening on the latest release when playing on 60fps mode. I was stuck at a white screen after beating the champion, and could not progress until disabling 60fps.

**Comment by jojobear13** [comment]
> This may still be happening on the latest release when playing on 60fps mode. I was stuck at a white screen after beating the champion, and could not progress until disabling 60fps.

The following footage was recorded using the patches [here](https://github.com/jojobear13/shinpokered/releases/tag/1.24.0) and played on the BGB emulator in 60 FPS mode. The game now plays properly from the end of the champion battle to the start of the credits.
https://github.com/jojobear13/shinpokered/assets/47074297/e43358ed-d356-499b-ad22-0a007dab4568

**Comment by jz-k** [comment]
Thanks! I was playing on the gameboy color core of the Analogue Pocket. It only happened the first time I finished the E4. All subsequent runs have finished correctly in 60fps mode.
