### ISSUE TITLE
Request: Add an option to not enable all 151 Pokémon?

### ISSUE THREAD

**Issue by pressRtowin** [jojobear13/shinpokered#297]
**Is your feature request related to bug or a functional problem?**
If so, do not create a request. Please submit a bug report instead.

No

**Is your feature [Within-Scope](https://github.com/jojobear13/shinpokered/blob/master/README.md#will-not-implement--out-of-scope) of the project?**
Please describe how your request fits within the scope of the project. It should adhere solely to Generation-1 Pokemon with a pre-1998 directive mindset. Requests that are determined to be out-of-scope will not be considered.

I believe so? It pertains to the original feel of each version so I'd say yes.

**Is your feature request related to a game-play problem?**
Is your request in response to something that frustrates you or otherwise deprecates your play experience? If so, please describe the problem in detail.

Yes, replayability of the different versions is diminished in the current state.

**Describe the feature you would like**
Write a clear and concise description of what you want to happen. Be as thorough as possible, and please include a detailed order of events (if any).

This might not be a popular opinion, but I actually enjoy that you can't get every Pokémon in just one game. I feel like it adds to the identity of each version and gives you a reason to play each. Any chance of either adding an option to disable this, or making a version of the patches with just that removed and all other additions intact? I know rarity is determined by version for some Pokemon right now, but an option to limit the encounters entirely to what was originally available in each game would be neat. Perhaps even the option to only unlock Pokemon not originally available in the game after defeating the elite four, if you want to still keep the game 100% beatable on its own.

**Describe alternatives you've considered**
Please include clear and concise descriptions of any alternative solutions or features you've considered.

See above

**Additional context**
Add any other context or screenshots/mock-ups/graphs/etc about the feature request.

N/A

**Comment by jojobear13** [comment]
This kind of thing is meant to be covered by the lite patches.
