### ISSUE TITLE
Seasfoam Isalnds Strong Current Disabled with One Boulder

### ISSUE THREAD

**Issue by wisp92** [jojobear13/shinpokered#30]
Tested in Lite Version.

In BF4 the strong current stops even if only the left boulder is placed to the final position.

I just noticed this, and I am well ahead of this point to roll back and check different behaviors but I'll check it thoroughly in a future playthrough. In the meantime, I post it here in case you want to check it even with this partial info.

EDIT: The problem was that entering from the right bank side didn't activate a JoyPad sequence.

**Comment by jojobear13** [comment]
fix implemented
