### ISSUE TITLE
Request: Lass acknowledges her Clefable

### ISSUE THREAD

**Issue by Healnavi** [jojobear13/shinpokered#305]
**Is your feature [Within-Scope](https://github.com/jojobear13/shinpokered/blob/master/README.md#will-not-implement--out-of-scope) of the project?**
Yes. This request is in response to an existing change not aligning with trainer dialogue.

**Describe the feature you would like**
Please amend dialogue discrepancy caused by trainer roster alteration.

The easternmost Lass on Route 8 has text referencing her original all-Clefairy team, but has a Clefairy/Clefable pair in Shin. She ends her battle saying "Stop! Don't be so mean to my Clefairy!" despite closing the fight with a Clefable and not being a trainer class that can swap Pokemon. When spoken to after battle, she says "I heard that Clefairy evolves when it's exposed to a Moon Stone." This is phrased as if she's relating a rumor, despite owning a Clefable. 

**Describe alternatives you've considered**
1. Battle end text should reference Clefable rather than Clefairy. She's interjecting, so she should reference the last Pokemon defeated.
2. Post-battle text should either become a statement by removing first line ("Clefairy evolves when it's exposed to a Moon Stone.") or relate to her own Clefable ("My Clefairy evolved when it was exposed to a Moon Stone.")

**Comment by jojobear13** [comment]
Good ideas all 'round. I'll keep this open as a reminder.
