### ISSUE TITLE
Request: Redf Image Hat feels wrong

### ISSUE THREAD

**Issue by dotmatrixgirl** [jojobear13/shinpokered#307]
**Is your feature [Within-Scope](https://github.com/jojobear13/shinpokered/blob/master/README.md#will-not-implement--out-of-scope) of the project?**
Hat sprite facing left and right of redf.png doesn't look correct compared to up/down sprites. I feel that the edited red sprite doesn't quite work the same way.

**Is your feature request related to a game-play problem?**
Graphically it was frustrating, changing it felt so much better to play. It was distracting me from the nostalgic experience. I do love the female option.

**Describe the feature you would like**
A hat that works a little better with perspective.

**Describe alternatives you've considered**
Attached is a corrected image done by myself. It was created for personal use. It compiled fine. I edited the image in GIMP. It's an edit of the included sprite, but I'd I'd love for it to be included.

**Additional context**

<img width="8" alt="redf" src="https://github.com/jojobear13/shinpokered/assets/54685652/b69dd730-52ac-466e-abe7-ca48bc3c3ece">

**Comment by jojobear13** [comment]
Internal decision was split. Decided to table graphics changes at this time.
