### ISSUE TITLE
Where is the shiny rate?

### ISSUE THREAD

**Issue by tyconway** [jojobear13/shinpokered#312]
I couldn't find a place to comment or message, so this may not be the appropriate spot.

What file affects the shiny rate of wild pokemon encountered?

**Comment by jojobear13** [comment]
There is no one particular thing that determines the shiny "rate" in generation 2 (and by extension generation 1). In the GB/C games, shininess is determined by a pokemon's randomly generated DVs. A pokemon can only be shiny if its DV bytes in binary are xx1xxxxx 10101010 with the 'x' meaning the bit can be a 1 or a 0. This pattern is checked in [the ShinyDVsChecker function](https://github.com/jojobear13/shinpokered/blob/7a32c806c2a66105086c1c383c5f9c11445afe8a/custom_functions/func_shiny.asm#L81C6-L81C6).

The actual functions for generating random numbers are kept in /engine/random.asm

/random.asm

**Comment by tyconway** [comment]
So if I drop the level 100 and Chansey requirements, and adjust the random check, would this do it? 

Original:
```
ShinyAttractFunction:
;make a 1 in 255 chance to force shiny DVs on a wild pokemon 
	call Random
	ret nz
	ld a, [wFontLoaded]
	set 7, a 
	ld [wFontLoaded], a
	ret
```

Proposed
```
ShinyAttractFunction:
    ; Generate a random number and check if it's less than 26 for a 1 in 10 chance
    call Random
    cp 26 ; 256 / 10 = 25.6, approximate to 26 for a 1 in 10 chance
    ret nc

    ; Set flag
    ld a, [wFontLoaded]
    set 7, a
    ld [wFontLoaded], a
    ret
```

**Comment by tyconway** [comment]
What would be the benefit of adjusting the random function itself? Does the ShinyAttractFunction only affect wild pokemon encounters, so starter pokemon and enemy trainer pokemon would be unaffected unless the random function is adjusted?

**Comment by jojobear13** [comment]
> What would be the benefit of adjusting the random function itself?

Direct control over the random numbers that are generated.

> Does the ShinyAttractFunction only affect wild pokemon encounters, so starter pokemon and enemy trainer pokemon would be unaffected unless the random function is adjusted?

Correct.
