### ISSUE TITLE
Request: Consistent Signpost Direction Order

### ISSUE THREAD

**Issue by Healnavi** [jojobear13/shinpokered#316]
**Is your feature [Within-Scope](https://github.com/jojobear13/shinpokered/blob/master/README.md#will-not-implement--out-of-scope) of the project?**
Yes. This request is about amending inconsistency in the signpost directions.

**Describe the feature you would like**
Please amend signpost text to give consistent directions to players.

Several signposts across Kanto give the player directions to navigate the region. The format for most of these signposts is
[Transitory Location] [Closer location from signpost] - [Farther location from signpost]
There are a few exceptions that are in this format but with a swapped location order: the Underground Path signposts by Vermilion and Lavender; the Cycling Road signpost closer to Fuchsia; the sign just west of Fuchsia. These list the distant location first and the close location second.

Every sign that gives directions follows the same pattern of identifying the closest area first, with signs near Lavender and Fuchsia on the sea route giving directions to the closer area, signs denoting dungeons being placed next to their entrances, etc.

**Describe alternatives you've considered**
Swap the stated locations on four signs:
1. (Route 6 signpost) Underground Path Vermilion City - Cerulean City
2. (Route 8 signpost) Underground Path Lavender Town - Celadon City
3. (Southern Route 17 signpost) Route 17 Fuchsia City - Celadon City
4. Route 18 Fuchsia City - Celadon City
This way the game gives the player pertinent directions that always tell them where they're coming from and where they're going.

**Comment by Healnavi** [comment]
Worth noting that these signposts could be interpreted as trying to convey the physical location of the city in text (first being north or west, second being south or east) due to the way it's rendered in the text box, but the first two examples in the game don't do this and instead follow the typical pattern (Route 1 Pallet - Viridian, Route 2 Viridian - Pewter). It could also be interpreted as where the player is coming from first in a typical playthrough, but the Celadon - Lavender UP sign doesn't fit this either. Regardless of developer intent, there's no single pattern. The suggestion given above is based on making the most sense for the player while being the least intrusive.

**Comment by jojobear13** [comment]
> Regardless of developer intent, there's no single pattern

The pattern is that Gamefreak dev that worked on this copy/pasted the text out of convenience.

**Comment by jojobear13** [comment]
added in commit eb1dbd874

**Comment by Healnavi** [comment]
Considering the Route 17 signpost is in a row of tightly-packed signposts (in the way that real life roads will space signs based on the speed of traffic), I'd argue that one's almost certainly meant for northbound players. That said, I get where you're coming from and respect the decision.
