### ISSUE TITLE
Request: Post-Game NPC Dialogue Edit

### ISSUE THREAD

**Issue by Healnavi** [jojobear13/shinpokered#317]
**Is your feature [Within-Scope](https://github.com/jojobear13/shinpokered/blob/master/README.md#will-not-implement--out-of-scope) of the project?**
Yes. This request is in response to Shin's post-game world state change not aligning with NPC dialogue.

**Describe the feature you would like**
Please amend dialogue discrepancies in the post-game, mostly based on the S.S. Anne.

The northernmost NPC on the deck of the S.S. Anne says "The party's over. The ship will be departing soon." no matter when the player talks to them. This includes after beating the Elite Four, when an NPC in Vermilion City remarks that the ship has returned due to massive blooms of Tentacool in nearby waters. The NPC's comment is no longer accurate to the situation: the original text warned the player that the S.S. Anne isn't a permanent part of the game world and will be leaving soon. It should be updated to not suggest it will leave again during play.

Similarly, the captain will always say, "Whew! Now that I'm not sick any more, I can sail anytime," even in the post-game. With the Tentacool bloom as the cause of the ship being stuck in the harbor instead of the captain's sea sickness, this dialogue doesn't make sense anymore. The captain's dialogue should be updated to not imply his sickness is why they're back in Vermilion.

An edge case is the Gym Guide. He shows up in the S.S. Anne, calling you Champ, when you engage in Shin's added tournament. However, he still says his iconic "Yo! Champ in making!" at Indigo Plateau after you've beaten the game.  All of his other post-gym dialogue avoids mentioning your champion status. All of the Elite Four, your rival, etc are also just vague enough in Nob's original script that they don't concretely say any successive Pokemon League challenge is your first, fitting in with the unlocked Unknown Dungeon and your League records on PC implying a progressed world state. Shin adds more things that convey the passage of time in the world state, so I believe this sticks out even more than in the original. I think it would make the post-game more consistent to slightly alter the Gym Guide's Indigo Plateau dialogue in the post-game.

**Describe alternatives you've considered**
1. NPC on deck stays close to original dialogue while indicating the changed world state. Suggestion: "The party's over. The ship's stuck here until the Tentacool clear out." ["will be departing" omitted to avoid suggestion that ship will leave]

2. The captain stays close to original dialogue without implying he's about to set sail. Suggestions: A. "Whew! Now that I'm not sick any more, I can sail just fine." [Statement about their previous departure instead of impending departure] B. "Whew! Glad I'm not sick any more. Too bad we can't set sail..." [Acknowledges inability to depart]

3. Gym Guide should acknowledge your rank when you're heading for a rematch. Suggestion: "Yo! Once and future Champ!" [Acknowledges having cleared game at least once, aligns with unchanged Elite Four dialogue implying Red is not reigning Champ and must have a rematch with the rival to get a new title entry in the Hall of Fame]

**Comment by jojobear13** [comment]
added in commit 39dcca763

**Comment by Healnavi** [comment]
Sorry, I noticed something with the rewrite in the commit. The new text for the guy on the deck says "Party's back on," but multiple NPCs on the S.S. Anne have dialogue related to the fact that the party's over and they're annoyed that they're stuck in Vermilion Harbor. Maybe change this to "Let's party!" to keep the status "No, there is not currently a party."?

This is REALLY minor. Sorry. Thanks for all you've done on this project, I can't think of anything else left to fix!

**Comment by jojobear13** [comment]
Done.
