### ISSUE TITLE
Question: Missing TMs in Pokemarts

### ISSUE THREAD

**Issue by lkstl** [jojobear13/shinpokered#331]
The README and the guide to new player functions states that **every** TM can be repurchased from Pokemarts.
However, after not finding TM 24 (Thunderbolt) in any mart ingame, I had a look at the [mart_invetories](https://github.com/jojobear13/shinpokered/blob/master/data/mart_inventories.asm) file. It seems like the following TMs are missing:

- TM 14 (Blizzard)
- TM 15 (Hyper Beam)
- TM 24 (Thunderbolt)

Is this on purpose or an oversight? Are there other means to reacquire these TMs?

**Comment by jojobear13** [comment]
Check the prize corner.
