### ISSUE TITLE
Request: Sticker art & language localization

### ISSUE THREAD

**Issue by antoine-jacquet** [jojobear13/shinpokered#332]
Hi, this is not really a feature request, but since you have a folder with box art I thought it could be worth asking: would it be possible to add custom cartridge sticker art as well, using the same alternative sprites that are used for the Shin box art?

Additionally, I don't know if you have thought about doing language localisations but would love to help with a French translation if I can.

**Comment by jojobear13** [comment]
The pokemon artwork used for the alt boxes is Ken Sugimori art made exclusively for the old Japanese Carddass trading cards. Dr. Lava was doing restorations some years ago. All it would take is a little skill with a good image editor.

![venusaur_carddass_drlava](https://github.com/jojobear13/shinpokered/assets/47074297/e0ce1352-0851-44c0-9cb6-afb1f1068117)
![blastoise_carddass_drlava](https://github.com/jojobear13/shinpokered/assets/47074297/b7603bbc-a492-420b-a043-027cfa3e9427)
![charizard_carddass_drlava](https://github.com/jojobear13/shinpokered/assets/47074297/333c4c60-60fd-4367-8a29-c50b3545e415)
![pikachu_carddass_drlava](https://github.com/jojobear13/shinpokered/assets/47074297/c8ba106a-8994-4fa2-b6c0-5a30ff5b7e17)

No plans to do localizations. That's something left for other people to take up.

**Comment by jojobear13** [comment]
Here is something I threw together. Not half bad.
![labelred](https://github.com/jojobear13/shinpokered/assets/47074297/63a3cb1f-2b50-4c7a-92df-f2ecccec4e97)

**Comment by tournepivoine** [comment]
Hi @antoine-jacquet, I made a complete french localisation of the Lite branch here if it can help:
https://github.com/tournepivoine/shinpokered-fr
