### ISSUE TITLE
Move water gun TM to Pewter City Pokemart

### ISSUE THREAD

**Issue by gotdapower** [jojobear13/shinpokered#333]
**Is your feature [Within-Scope](https://github.com/jojobear13/shinpokered/blob/master/README.md#will-not-implement--out-of-scope) of the project?**
Since TMs have already been placed at pokemarts, I would say yes. 

**Is your feature request related to a game-play problem?**
Many water-type pokemon (Psyduck, goldeen, tentacool, staryu) don't get a water-type move prior to either leveling up past Brock, or getting the water gun TM at Mt. Moon. This significantly reduces the number of pokemon that can realistically beat Brock without significant overlevelling. The purchase of the TM in Vermillion is not useful since Bubblebeam is already available at that point.

**Describe the feature you would like**
Move water gun TM to Pewter City Pokemart.

**Describe alternatives you've considered**
Could hide the TM, move it to Veridian City

**Comment by jojobear13** [comment]
Already addressed in commit d9df6a44838af6aaf43892cb61464a0aae87edac. This moves the Water Gun TM item ball to the top floor of the Pewter Museum, and in doing so gives a little more purpose in paying the entrance fee and exploring the place. It's former location in Mt. Moon is occupied by a Super Repel.
