### ISSUE TITLE
Request: Dampen level scaling for regular trainers

### ISSUE THREAD

**Issue by crystallikelaw** [jojobear13/shinpokered#337]
Lower trainer scaling for regular trainers. 

With scaling it's difficult to (re)match them to train up weaker pokemon because they're too strong. Especially in the early game, it's hard to fight 2/3x lvl 13 Beedrills with a lvl 13 starter and, say, a lvl 4 Nidoran and/or Rattata, necessitating grinding on wild pokemon. And since you have to switch the starter in to defeat them (assuming you can even defeat them), the starter gets even more overlevelled and the cycle perpetuates.

Possible alternatives: have normal trainers scale to avg party level/2nd or 3rd highest level pokemon or something of the sort? And keep boss trainers scaled to your highest level pokemon.

**Comment by jojobear13** [comment]
implemented in the following commits:
9cc0cb03892821827077434f558a8bd8e93b21ef
2eab58f05d9e2c85b16990a7fa84cf7dae34a7e1
950eeaf81177c746db56abfba20ce801d2b45769
