### ISSUE TITLE
Bug: Full non-tiered randomization not activating

### ISSUE THREAD

**Issue by gotdapower** [jojobear13/shinpokered#338]
**What emulator and/or hardware are you are using?**
BGB

**Which patch are you using?**
v.1.24.5M from github

**What version of this project are you using?**
Main branch origback

**What is the problem you encountered?**
I have re-randomized the encounters a number of times and suspect that the full randomization option is not working, since I am still not encountering many stronger pokemon until I reach further areas of the game where they are clearly appearing in stronger "slots", for example the higher level encounters in diglett cave, while surfing or in the safari zone. The ones that stick out to me (which I was hoping to encounter and have a chance of using during nuzlocke mode) are the pokemon that don't evolve like Tauros, electabuzz, magmar, etc. Currently the only pokemon I am finding who don't evolve are the ones I assume are already in Tier A - Lickitung, Porygon and Onix.

**Expected behavior**
Reviewing the previous issue (309), I was expecting the 108 pokemon in tiers A/B/C to be available as wild encounters as early as route 1.

**Comment by jojobear13** [comment]
The flag is not getting set properly in the NPC script.

In the meantime, so you don't have to wait for the next update, you can activate it with the gameshark code 018061d8.

**Comment by jojobear13** [comment]
![image](https://github.com/jojobear13/shinpokered/assets/47074297/4b87387c-ab28-4868-9b36-63d56ca0c1c0)

**Comment by jojobear13** [comment]
fixed in commit 6dbc75617eb7eff6cc1448ab170f6a183a0c95f5
