### ISSUE TITLE
Evolved Forms Access to Previous Learn-Set

### ISSUE THREAD

**Issue by wisp92** [jojobear13/shinpokered#38]
Tested in Lite Version.

After evolution, the PKMN will try to learn past moves in its learn-set. To recreate start with a PKMN and PKMN Move that can be learned through a level up by both the basic and the evolved form, e.g., Skull Bush for Squirtle. Let X be the level at which evolved form learns this move, e.g., 39 in the example.
Evolve the basic form at a level greater than X.

**Comment by wisp92** [comment]
Update: I figured out what causes the bug. In your fix for the skipped moves, you are starting the check from PKMN evolution required instead of its level in the start of the battle. I'll try to provide a fix.

**Comment by jojobear13** [comment]
Pull slated for testing.
