### ISSUE TITLE
Possibly Issue with Rescaling

### ISSUE THREAD

**Issue by wisp92** [jojobear13/shinpokered#40]
Tested in Master Branch.

I observed something weird regarding trainer rescaling but I am not sure if it's an issue or a feature. I need to read the code. When I fought the rival for the first time my first PKMN was level 10, and the rival's both PKMN were at level 12. My first PKMN gained a level bu I lost the fight. Battling the rival again changed the his PKMN levels. Specifically to 11 and 12, which made the battle easier. Can you verify if this is indeed an issue and I can help look into it?

**Comment by jojobear13** [comment]
Working as intended. The trainer scaling adds a random number to the levels of trainer rosters. It was done to keep nuzlocke players on their toes.
