### ISSUE TITLE
Suggestion for Rescaling

### ISSUE THREAD

**Issue by wisp92** [jojobear13/shinpokered#41]
Would it be possible for the trainers to rescale based on the strongest PKMN in the team instead of the first one? This would give the same difficult experience without the following drawbacks:

1. The strongest PKMN to always gain experience
2. Leveling up the weak PKMN without changing to shift battles. Putting the weak PKMN first and then change to a stronger one is the tactic (also suggested in-game) to train weak PKMN.
3. To effectively disable tactics in the first turn, e.g., we know that a trainer uses a specific kind of PKMN but we are forced to start with the strongest PKMN anyway

EDIT: The rescaling would be a bit more consistent too. Leveling up the strongest PKMN is far less likely than changing the order of PKMN. The later could even happen just if a PKMN fainted while the first needs work.

**Comment by jojobear13** [comment]
Done. It was easier to implement now that wStartBattleLevels exists.
