### ISSUE TITLE
Payment Scales to... Player PKMN?!

### ISSUE THREAD

**Issue by wisp92** [jojobear13/shinpokered#43]
Wow, this is the first time I notice but actually the money you gain both from a trainer battle and from Pay Day scale with the player PKMN's level. Isn't it much more intuitive and rewarding to scale based on the opponent PKMN's level? Is it an oversight?

EDIT: Fainting a Lvl 100 Onix using only Pay Day... this is a serious pay out.

**Comment by jojobear13** [comment]
Are you playing with trainer scaling on?

Trainer money is based on their mons levels. Pay day money is based on the user’s level. This is how it is supposed to work

**Comment by wisp92** [comment]
Yes you right, I am using rescaling. 

However, I'll try to do some analysis to point out some issues:

First, let's write down what we know about the mechanics:
1. Rescaling leads to faster Lvl ups
2. Rescaling leads to higher Lvl Trainer battles
3. Upon losing, the player loses half the money
4. Upon winning, the player gains Last PKMN Lvl times Opponent's Base
5. Trainers can be re-battled
6. PayDay factor is 5
7. PayDay can be acquired early
8. PayDay can be used early (Pikachu)

To keep things interesting we would like in general the story to unravel in a good pace, not too-easy but not boring. The original is too-easy and the rescaling is a very good idea to make things just hard enough. The main problem here is that the player simply lacks the resources to get all the potential from the rescaling:

Due to (1) and (2) we can expect more losses, especially at the start of the game where PKMN do not have their full arsenal yet and rely more on power. By (3) and (4) this means that player's money stay in very low levels and it's difficult to acquire and use potions etc. to help with the difficult battles. PayDay (7) and (8) is a good solution, especially with the updated factor (6) since player's PKMN will go to Lvl 10+ really fast in this setting and a potion costs 300. But still, we force the player to take detours in an increasing rate to acquire this money from low Lvl PKMN in the wild or through re-battling trainers (5) with one PKMN for maximum potential (4).

I suggest the following:
1. Losing should decrease the money like in Generation IV and onwards. This is to encourage retrying the difficult point a few times before taking a detour and for fairness since opponents are scaled to player's Lvl.
2. Re-battling should provide lowered income and solely used for Lvl balancing purposes to discourage detours.
3. If the above still don't provide enough push the PayDay factor could go back to 2 when rescaling is active.

Personally I enjoy the rescaling and I find a really good idea to be applied in general. I hope you find my suggestion helpful.

**Comment by jojobear13** [comment]
Payday is pretty pointless with a factor of 2x. That's why the amulet coin was created in gen 2 and payday was given a base of 5x in gen 3.

As for trainer scaling, that was only added due to fan feedback. Originally it only applied to the random trainer generator as a way to grind to level 100. Turning it on isn't really meant to give a balanced experience, and it is more for post-game adventuring with your post-E4 team. But hey, Kaizo hacks exist so some people enjoy a constant stream of unfair uphill battles.
