### ISSUE TITLE
Dragon Rage show Critical Hit Text

### ISSUE THREAD

**Issue by wisp92** [jojobear13/shinpokered#44]
Tested in Master Branch.

Although the critical hit modification for Dragon Rage is not applied as it should, the text still appears. I can't test for other fixed-damage moves at the moment.

**Comment by jojobear13** [comment]
Only way I see this happening is if somehow wCriticalHitOrOHKO doesn't get cleared. Perhaps if the mon going first gets a critical hit then the mon going second uses dragon rage. I put in some lines to reset if a static move is used.
