### ISSUE TITLE
Crash after choosing starter

### ISSUE THREAD

**Issue by keram88** [jojobear13/shinpokered#46]
Hello,
The master branch currently has an issue where the game plays many crys, corrupts dialogue text, then crashes after choosing a starter Pokemon. This appears in commit 7db399425c7e3ebecc6d07189ca93b59d9b8b856.

Thanks.

**Comment by jojobear13** [comment]
Fixed in bde93e8dcaca51b8f4a1afafca86ff9795189855. New patches uploaded for master and lite branches.
