### ISSUE TITLE
Trade Evolutions Do Not Happen With Vanilla

### ISSUE THREAD

**Issue by kactuus** [jojobear13/shinpokered#61]
I traded a Kadabra over to a copy of vanilla red and both the data for the Kadabra as far as stats, OT, TID, and XP were corrupted and the trade evolution didn't occur. PKHeX didn't recognize that there was a pokemon in the party slot either. Trade was done on BGB emulator on the current build. Evolution didn't happen when traded over to Red or when it was traded back to Shin Blue.

**Comment by kactuus** [comment]
You might want to add that to the documentation in that case rather than have someone incidentally corrupt the Pokemon data without recourse due to the game immediately saving.

**Comment by jojobear13** [comment]
I'm going to reopen this for the time being while I do some tests with real hardware. Not sure if this is caused by BGB's link emulation or the placement of pokemon base data in rom.

**Comment by jojobear13** [comment]
Tested this with real hardware and master branch 1.16 flashed to a bootleg cart. A machoke was traded to a retail Red USA cartridge and successfully evolved to machamp. A kadabra was was traded from the retail Red cart to the bootleg cart and successfully evolved to alakazam. This experiment was repeated using two linked instances of BGB version 1.5.8, and the same successful trades and evolutions occurred.
