### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by WilliamOfBlobs** [jojobear13/shinpokered#75]
Basically, I tried compiling both the lite and lite_dev branches earlier, and... I get the following error. Just see the attachments... I'm unsure of what the exact problem might be. Could be a change in rgbds 0.4.2, maybe?
![Screenshot_20201214-021902](https://user-images.githubusercontent.com/75296966/102051577-c7c54780-3db2-11eb-87ac-5b4188c23444.png)

**Comment by jojobear13** [comment]
> Could be a change in rgbds 0.4.2, maybe?

Yes. Try using 0.4.1 or 0.4.0.
