### ISSUE TITLE
Powerplant encounter data is not vanilla in the lite branch

### ISSUE THREAD

**Issue by Vas0sky** [jojobear13/shinpokered#99]
I've stumbled upon porygon earlier in red, went to check the code and found that the encounter data for the lite version is the same as the master version (so more electabuzz and a chance for porygon in red, while more raichu and a chance for electabuzz in blue/green). I believe this is a bug, since other encounters sheets are the same as in the vanilla game.

**Comment by jojobear13** [comment]
Good catch. I'll slate it for the next update
